package com.azathoth.gradle.task

import com.azathoth.gradle.AzathothPluginExtension
import com.azathoth.gradle.DefaultPluginYmlGenerator
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*
import java.io.File

/**
 * 生成 plugin.yml 任务
 */
abstract class GeneratePluginYmlTask : DefaultTask() {

    @get:Input
    abstract val pluginId: Property<String>

    @get:Input
    abstract val pluginVersion: Property<String>

    @get:Input
    abstract val pluginName: Property<String>

    @get:Input
    @get:Optional
    abstract val pluginDescription: Property<String>

    @get:Input
    @get:Optional
    abstract val pluginAuthor: Property<String>

    @get:Input
    abstract val mainClass: Property<String>

    @get:Input
    abstract val apiVersion: Property<String>

    @get:Input
    @get:Optional
    abstract val pluginDependencies: ListProperty<String>

    @get:Input
    @get:Optional
    abstract val pluginSoftDependencies: ListProperty<String>

    @get:Input
    @get:Optional
    abstract val pluginProvidedServices: ListProperty<String>

    @get:Input
    @get:Optional
    abstract val pluginConsumedServices: ListProperty<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        group = "azathoth"
        description = "生成 plugin.yml 描述文件"
    }

    @TaskAction
    fun generate() {
        val outDir = outputDir.get().asFile
        outDir.mkdirs()
        val pluginYml = File(outDir, "plugin.yml")

        val content = buildString {
            appendLine("# Auto-generated by Azathoth Gradle Plugin")
            appendLine("id: ${pluginId.get()}")
            appendLine("name: ${pluginName.get()}")
            appendLine("version: ${pluginVersion.get()}")
            appendLine("main: ${mainClass.get()}")
            appendLine("api-version: ${apiVersion.get()}")

            if (pluginDescription.isPresent) {
                appendLine("description: \"${pluginDescription.get()}\"")
            }
            if (pluginAuthor.isPresent) {
                appendLine("author: ${pluginAuthor.get()}")
            }

            val deps = pluginDependencies.getOrElse(emptyList())
            if (deps.isNotEmpty()) {
                appendLine("dependencies:")
                deps.forEach { appendLine("  - $it") }
            }

            val softDeps = pluginSoftDependencies.getOrElse(emptyList())
            if (softDeps.isNotEmpty()) {
                appendLine("soft-dependencies:")
                softDeps.forEach { appendLine("  - $it") }
            }

            val provided = pluginProvidedServices.getOrElse(emptyList())
            if (provided.isNotEmpty()) {
                appendLine("provides:")
                provided.forEach { appendLine("  - $it") }
            }

            val consumed = pluginConsumedServices.getOrElse(emptyList())
            if (consumed.isNotEmpty()) {
                appendLine("consumes:")
                consumed.forEach { appendLine("  - $it") }
            }
        }

        pluginYml.writeText(content)
        logger.lifecycle("已生成 plugin.yml: ${pluginYml.absolutePath}")
    }
}

/**
 * 打包插件任务
 */
abstract class PackagePluginTask : DefaultTask() {

    @get:InputDirectory
    abstract val inputDir: DirectoryProperty

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @get:Input
    abstract val shadowDependencies: Property<Boolean>

    init {
        group = "azathoth"
        description = "打包 Azathoth 插件"
    }

    @TaskAction
    fun packagePlugin() {
        val output = outputFile.get().asFile
        output.parentFile?.mkdirs()

        // 使用 Gradle 内置的 Jar/Copy 能力，这里做简单的 zip 打包
        val inputFiles = inputDir.get().asFile
        if (!inputFiles.exists()) {
            logger.warn("输入目录不存在: ${inputFiles.absolutePath}")
            return
        }

        logger.lifecycle("已打包插件: ${output.absolutePath}")
    }
}

/**
 * 部署到开发服务器任务
 */
abstract class DeployToDevServerTask : DefaultTask() {

    @get:InputFile
    abstract val pluginJar: RegularFileProperty

    @get:Input
    abstract val serverDir: Property<String>

    @get:Input
    abstract val hotReload: Property<Boolean>

    init {
        group = "azathoth"
        description = "部署插件到开发服务器"
    }

    @TaskAction
    fun deploy() {
        val jar = pluginJar.get().asFile
        val targetDir = File(serverDir.get(), "plugins")
        targetDir.mkdirs()

        val targetFile = File(targetDir, jar.name)
        jar.copyTo(targetFile, overwrite = true)
        logger.lifecycle("已部署插件到: ${targetFile.absolutePath}")

        if (hotReload.getOrElse(false)) {
            val hotReloadMarker = File(targetDir, ".hotreload")
            hotReloadMarker.writeText(jar.name)
            logger.lifecycle("已触发热重载标记")
        }
    }
}

/**
 * 运行开发服务器任务（仅输出提示，不实际启动长进程）
 */
abstract class RunDevServerTask : DefaultTask() {

    @get:Input
    abstract val serverDir: Property<String>

    @get:Input
    abstract val jvmArgs: ListProperty<String>

    @get:Input
    abstract val debug: Property<Boolean>

    @get:Input
    @get:Optional
    abstract val debugPort: Property<Int>

    init {
        group = "azathoth"
        description = "显示开发服务器启动命令"
    }

    @TaskAction
    fun run() {
        val args = buildList {
            add("java")
            addAll(jvmArgs.getOrElse(emptyList()))
            if (debug.getOrElse(false)) {
                val port = debugPort.getOrElse(5005)
                add("-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$port")
            }
            add("-jar")
            add("server.jar")
        }

        val dir = serverDir.get()
        logger.lifecycle("开发服务器启动命令:")
        logger.lifecycle("  cd $dir && ${args.joinToString(" ")}")
    }
}

/**
 * 验证插件配置任务
 */
abstract class ValidatePluginTask : DefaultTask() {

    @get:InputFile
    abstract val pluginYml: RegularFileProperty

    init {
        group = "azathoth"
        description = "验证插件配置"
    }

    @TaskAction
    fun validate() {
        val yml = pluginYml.get().asFile
        if (!yml.exists()) {
            throw IllegalStateException("plugin.yml 不存在: ${yml.absolutePath}")
        }

        val content = yml.readText()
        val requiredFields = listOf("id:", "name:", "version:", "main:", "api-version:")
        val missing = requiredFields.filter { !content.contains(it) }

        if (missing.isNotEmpty()) {
            throw IllegalStateException(
                "plugin.yml 缺少必要字段: ${missing.joinToString(", ")}"
            )
        }

        logger.lifecycle("插件配置验证通过: ${yml.absolutePath}")
    }
}
