apiVersion: v1
kind: Service
metadata:
  name: {{ include "azathoth.fullname" . }}-guild-service
  labels:
    {{- include "azathoth.labels" . | nindent 4 }}
    app.kubernetes.io/component: guild-service
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "azathoth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: guild-service
