package com.azathoth.gradle

import java.io.File

/**
 * plugin.yml 生成器接口
 */
interface PluginYmlGenerator {
    /**
     * 生成 plugin.yml 文件
     */
    fun generate(extension: AzathothPluginExtension, outputDir: File)

    /**
     * 验证配置
     */
    fun validate(extension: AzathothPluginExtension): ValidationResult
}

/**
 * 验证结果
 */
interface ValidationResult {
    val valid: Boolean
    val errors: List<String>
    val warnings: List<String>
}

/**
 * 默认验证结果实现
 */
data class DefaultValidationResult(
    override val valid: Boolean,
    override val errors: List<String> = emptyList(),
    override val warnings: List<String> = emptyList()
) : ValidationResult

/**
 * 默认 plugin.yml 生成器实现
 */
class DefaultPluginYmlGenerator : PluginYmlGenerator {

    override fun generate(extension: AzathothPluginExtension, outputDir: File) {
        val result = validate(extension)
        if (!result.valid) {
            throw IllegalStateException(
                "插件配置验证失败:\n${result.errors.joinToString("\n") { "  - $it" }}"
            )
        }

        outputDir.mkdirs()
        val pluginYml = File(outputDir, "plugin.yml")

        val content = buildString {
            appendLine("# Auto-generated by Azathoth Gradle Plugin")
            appendLine("id: ${extension.id.get()}")
            appendLine("name: ${extension.name.get()}")
            appendLine("version: ${extension.version.get()}")
            appendLine("main: ${extension.mainClass.get()}")
            appendLine("api-version: ${extension.apiVersion.get()}")

            if (extension.description.isPresent) {
                appendLine("description: \"${extension.description.get()}\"")
            }
            if (extension.author.isPresent) {
                appendLine("author: ${extension.author.get()}")
            }

            val deps = extension.dependencies.getOrElse(emptyList())
            if (deps.isNotEmpty()) {
                appendLine("dependencies:")
                deps.filter { !it.optional }.forEach { dep ->
                    appendLine("  - id: ${dep.pluginId}")
                    if (dep.versionRange != "*") {
                        appendLine("    version: \"${dep.versionRange}\"")
                    }
                }
            }

            val softDeps = extension.softDependencies.getOrElse(emptyList()) +
                deps.filter { it.optional }.map { it.pluginId }
            if (softDeps.isNotEmpty()) {
                appendLine("soft-dependencies:")
                softDeps.forEach { appendLine("  - $it") }
            }

            val provided = extension.providedServices.getOrElse(emptyList())
            if (provided.isNotEmpty()) {
                appendLine("provides:")
                provided.forEach { appendLine("  - $it") }
            }

            val consumed = extension.consumedServices.getOrElse(emptyList())
            if (consumed.isNotEmpty()) {
                appendLine("consumes:")
                consumed.forEach { appendLine("  - $it") }
            }
        }

        pluginYml.writeText(content)
    }

    override fun validate(extension: AzathothPluginExtension): ValidationResult {
        val errors = mutableListOf<String>()
        val warnings = mutableListOf<String>()

        if (!extension.id.isPresent || extension.id.get().isBlank()) {
            errors += "插件 id 不能为空"
        }
        if (!extension.name.isPresent || extension.name.get().isBlank()) {
            errors += "插件 name 不能为空"
        }
        if (!extension.mainClass.isPresent || extension.mainClass.get().isBlank()) {
            errors += "插件 mainClass 不能为空"
        }
        if (!extension.version.isPresent || extension.version.get().isBlank()) {
            errors += "插件 version 不能为空"
        }
        if (!extension.description.isPresent) {
            warnings += "建议设置插件 description"
        }
        if (!extension.author.isPresent) {
            warnings += "建议设置插件 author"
        }

        return DefaultValidationResult(
            valid = errors.isEmpty(),
            errors = errors,
            warnings = warnings
        )
    }
}
